### ISSUE TITLE
Can you help me how to send a console command?

### ISSUE THREAD

**Issue by Bazimek** [dexsper/RustRcon#1]
Hello, can you help me how to send a console command with this?

**Comment by dexsper** [comment]
Library has few command types, and one of them is:

[https://github.com/dexsper/RustRcon/blob/master/Types/Commands/Server/ConsoleCommand.cs](ConsoleCommand)


For example

```C#
rconClient.SendCommand(new ConsoleCommand("command", (x) =>
{
     //Command response
}));
```
